apiVersion: v1
kind: Pod
metadata:
  name: result-app
  labels:
    app: result-app
    appType: frontend
spec:
  containers:
    - name: vote-app
      image: saurabhd2106/result-app
      ports: 
        - containerPort: 80