apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis-app
    appType: frontend
spec:
  containers:
    - name: redis
      image: redis:5.0-alpine3.10
      ports: 
        - containerPort: 6379