apiVersion: v1
kind: Service
metadata:
  name: db
  label:
    appType: frontend
spec:
  type: ClusterIP 
  selector:
    appType: frontend
  ports: 
    - name: http
      port: 5432 # Service Port
      targetPort: 5432 # Container Port