apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP 
  selector:
    appType: backend
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 3000 # Container Port