apiVersion: v1
kind: Service
metadata:
  name: result-service 
spec:
  type: NodePort 
  selector:
    appType: frontend
  ports: 
    - name: http
      port: 81 # Service Port
      targetPort: 80 # Container Port
      nodePort: 31231 # NodePort