apiVersion: v1
kind: Service
metadata:
  name: result-service 
spec:
  type: NodePort 
  selector:
    type: backend
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 3000 # Container Port
      nodePort: 31231 # NodePort